version: "3.7"
services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    hostname: caddy
    #restart: always
    ports:
      - "880:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/web/index.html:/usr/share/caddy/index.html
      - ./data/caddy_data:/data
    deploy: #限制资源占用
      resources:
        limits:
          cpus: '1'
          memory: 200M
