version: "3"
services:
  dns-server:
    image: jpillora/dnsmasq
    container_name: dns-server
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - HTTP_USER=guanph
      - HTTP_PASS=guanphAdmin
    ports:
      - "53:53/udp"
      - "5380:8080"
    volumes:
      - "./conf/dnsmasq.conf:/etc/dnsmasq.conf"
    deploy: #限制资源占用
      resources:
        limits:
          cpus: '0.3'
          memory: 100M