version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    hostname: jenkins
    #environment:
    #  #JAVA_OPTS: -Dhudson.footerURL=http://mycompany.com
    #restart: always
    ports:
      - "6666:8080"
      - "50000:50000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jenkins_home:/var/jenkins_home
    deploy: #限制资源占用
      resources:
        limits:
          cpus: '1'
          memory: 200M