version: "3"
services:
  mariadb:
    image: mariadb:latest 
    hostname: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - "13306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/:/etc/mysql/conf.d
      - ./logs/:/logs/
      - ./database/:/var/lib/mysql
    deploy: #限制资源占用
      resources:
        limits:
          cpus: '1'
          memory: 200M
