version: '3'

services:

    nps_docker:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        container_name: nps_docker
        ports:
            - "3100-3199:3100-3199"
            - "80:80"
            - "8080:8080"
            - "443:443"
            - "8024:8024"
        volumes:
            - ./conf:/nps/conf

